/**
 * lib/mcpAuth.ts — Per-user identity resolution for MCP-facing routes.
 *
 * The MCP server (mcp/) is a separate local process that calls the Next.js
 * API over HTTP, attaching a per-user token as the `x-mcp-token` header
 * (generated by a logged-in user via `POST /api/account/mcp-token` — see
 * lib/auth.ts's `resolveRequestUser`, which tries the session cookie first
 * and falls back to `resolveMcpUser` below).
 *
 * `mcp/src/http.ts` / `mcp/src/tools.ts` are unchanged by this: MCP still
 * sends one opaque string as `x-mcp-token`, same as before. Only what that
 * string resolves to changed — a hashed McpApiToken row instead of a single
 * shared secret.
 */

import { NextRequest } from 'next/server'
import { createHash } from 'crypto'
import { prisma } from '@/lib/db'

export function hashMcpToken(rawToken: string): string {
  return createHash('sha256').update(rawToken).digest('hex')
}

/**
 * Resolves the calling MCP process to a `userId`, or `null` if it cannot be
 * identified. Never falls through to an open/no-op state when a token is
 * present but invalid or revoked — only the complete absence of a token
 * consults the non-production dev-user fallback.
 */
export async function resolveMcpUser(request: NextRequest): Promise<string | null> {
  const provided = request.headers.get('x-mcp-token')?.trim()

  if (provided) {
    const tokenHash = hashMcpToken(provided)
    const token = await prisma.mcpApiToken.findFirst({
      where: { tokenHash, revokedAt: null },
    })
    if (!token) return null // invalid/revoked token present ⇒ never fall through

    prisma.mcpApiToken
      .update({ where: { id: token.id }, data: { lastUsedAt: new Date() } })
      .catch(() => { /* non-critical — best-effort usage tracking */ })

    return token.userId
  }

  if (process.env.NODE_ENV !== 'production' && process.env.MCP_DEV_USER_EMAIL) {
    const devUser = await prisma.user.findUnique({
      where: { email: process.env.MCP_DEV_USER_EMAIL.trim().toLowerCase() },
    })
    return devUser?.id ?? null
  }

  return null
}
