#!/usr/bin/env npx tsx
/**
 * scripts/oracle/analyze_oracle.ts — task 9.2/9.3 analysis (read-only).
 *
 * Cross-references scripts/oracle/output/ashtakoota_oracle_raw.json (PyJHora's
 * raw sweep — git-ignored, generated by generate_oracle.py, never imported
 * itself) against this repo's OWN engine/compute/matchmaking.ts, by calling
 * the real `computeAshtakootaMatch` for every (boy, girl) combination and
 * diffing against PyJHora's `poroutham` results for that same combination.
 *
 * Never re-derives PyJHora's lookup tables by hand and never modifies
 * matchmakingTables.ts — this script only prints a report. Task 9.3's actual
 * table edits (if any) are a separate, deliberate step requiring sign-off.
 *
 * Usage:
 *   npx tsx scripts/oracle/analyze_oracle.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import { computeAshtakootaMatch, type MatchNativeInput } from '../../engine/compute/matchmaking'
import { taraRemainder, isTaraInauspicious } from '../../engine/compute/matchmakingTables'
import type { KootaKey } from '../../engine/compute/types'

const RAW_PATH = path.join(__dirname, 'output', 'ashtakoota_oracle_raw.json')

interface OracleEntry {
  boy_nakshatra: number
  boy_pada: number
  girl_nakshatra: number
  girl_pada: number
  poroutham: Record<string, { method: string; result?: unknown; error?: string }>
  error?: string
}

const raw = JSON.parse(fs.readFileSync(RAW_PATH, 'utf8')) as {
  combination_count: number
  error_count: number
  results: OracleEntry[]
}

const KOOTA_KEYS: KootaKey[] = ['varna', 'vashya', 'tara', 'yoni', 'grahaMaitri', 'gana', 'bhakoot', 'nadi']

function pyPoints(entry: OracleEntry, key: KootaKey): number | null {
  const r = entry.poroutham[key]?.result
  if (!Array.isArray(r) || typeof r[0] !== 'number') return null
  return r[0]
}

// ─── Step 1: calibrate boy/girl -> groom/bride direction ─────────────────
// Varna's rule ("1 point iff groom's varna rank >= bride's") is the single
// most classically unambiguous, unflagged cell in the whole module. Whichever
// hypothesis makes OUR OWN scoreVarna agree with PyJHora's varna_porutham
// almost everywhere is the correct boy/girl mapping — decided empirically
// from all 11,664 rows, not assumed.

function scoreHypothesis(boyIsGroom: boolean) {
  let matched = 0
  let total = 0
  const mismatchSamples: { boy: [number, number]; girl: [number, number]; ours: number; pyjhora: number }[] = []
  for (const entry of raw.results) {
    if (entry.error) continue
    const boy: MatchNativeInput = {
      nakshatraNumber: entry.boy_nakshatra,
      padaNumber: entry.boy_pada,
      role: boyIsGroom ? 'groom' : 'bride',
    }
    const girl: MatchNativeInput = {
      nakshatraNumber: entry.girl_nakshatra,
      padaNumber: entry.girl_pada,
      role: boyIsGroom ? 'bride' : 'groom',
    }
    const result = computeAshtakootaMatch(boy, girl)
    const varna = result.kootas.find((k) => k.key === 'varna')!
    const py = pyPoints(entry, 'varna')
    if (py === null) continue
    total++
    if (Math.abs(py - varna.points) < 1e-9) {
      matched++
    } else if (mismatchSamples.length < 6) {
      mismatchSamples.push({
        boy: [entry.boy_nakshatra, entry.boy_pada],
        girl: [entry.girl_nakshatra, entry.girl_pada],
        ours: varna.points,
        pyjhora: py,
      })
    }
  }
  return { matched, total, rate: total ? matched / total : 0, mismatchSamples }
}

const hypA = scoreHypothesis(true) // boy = groom, girl = bride
const hypB = scoreHypothesis(false) // boy = bride, girl = groom

console.log('═══ STEP 1: boy/girl ↔ groom/bride direction calibration (via Varna) ═══')
console.log(`Hypothesis A (boy=groom, girl=bride): ${hypA.matched}/${hypA.total} = ${(hypA.rate * 100).toFixed(2)}% agree with our scoreVarna`)
console.log(`Hypothesis B (boy=bride, girl=groom): ${hypB.matched}/${hypB.total} = ${(hypB.rate * 100).toFixed(2)}% agree with our scoreVarna`)

const boyIsGroom = hypA.rate >= hypB.rate
console.log(`\n=> Adopting: ${boyIsGroom ? 'boy=groom, girl=bride' : 'boy=bride, girl=groom'} (higher agreement rate) for all analysis below.\n`)

if (Math.max(hypA.rate, hypB.rate) < 0.95) {
  console.log('WARNING: even the better hypothesis agrees on Varna in under 95% of rows.')
  console.log('Sample disagreements (winning hypothesis):', JSON.stringify((boyIsGroom ? hypA : hypB).mismatchSamples, null, 2))
}

// ─── Step 2: full run under the calibrated direction, bucketed per koota ──

interface Bucket {
  ourPoints: number
  pyValues: Map<number, number> // pyjhora point value -> count observed
  sampleEvidence: unknown
}

const buckets: Record<KootaKey, Map<string, Bucket>> = {
  varna: new Map(), vashya: new Map(), tara: new Map(), yoni: new Map(),
  grahaMaitri: new Map(), gana: new Map(), bhakoot: new Map(), nadi: new Map(),
}

const koootaMismatchTotals: Record<KootaKey, { match: number; mismatch: number }> = {
  varna: { match: 0, mismatch: 0 }, vashya: { match: 0, mismatch: 0 }, tara: { match: 0, mismatch: 0 },
  yoni: { match: 0, mismatch: 0 }, grahaMaitri: { match: 0, mismatch: 0 }, gana: { match: 0, mismatch: 0 },
  bhakoot: { match: 0, mismatch: 0 }, nadi: { match: 0, mismatch: 0 },
}

function bucketKeyFor(key: KootaKey, evidence: any): string {
  const b = evidence.bride
  const g = evidence.groom
  switch (key) {
    case 'varna': return `${b.varna}(${b.rank})->${g.varna}(${g.rank})`
    case 'vashya': return [b.vashya, g.vashya].sort().join('|')
    case 'yoni': return [b.yoniAnimal, g.yoniAnimal].sort().join('|')
    case 'gana': return `${b.gana}->${g.gana}`
    case 'grahaMaitri': {
      if (evidence.rule === 'grahaMaitri.same_lord') return 'SAME_LORD'
      return `${b.relationToGroomLord}|${g.relationToBrideLord}`
    }
    case 'tara': return 'ALL' // aggregate only (bidirectional remainder rule, not table-based)
    case 'bhakoot': return 'ALL'
    case 'nadi': return b.nadi === g.nadi ? 'SAME' : 'DIFFERENT'
    default: return 'ALL'
  }
}

for (const entry of raw.results) {
  if (entry.error) continue
  const boy: MatchNativeInput = {
    nakshatraNumber: entry.boy_nakshatra,
    padaNumber: entry.boy_pada,
    role: boyIsGroom ? 'groom' : 'bride',
  }
  const girl: MatchNativeInput = {
    nakshatraNumber: entry.girl_nakshatra,
    padaNumber: entry.girl_pada,
    role: boyIsGroom ? 'bride' : 'groom',
  }
  const result = computeAshtakootaMatch(boy, girl)
  for (const k of result.kootas) {
    const key = k.key
    const py = pyPoints(entry, key)
    if (py === null) continue
    if (Math.abs(py - k.points) < 1e-9) koootaMismatchTotals[key].match++
    else koootaMismatchTotals[key].mismatch++

    const bucketKey = bucketKeyFor(key, k.evidence)
    const map = buckets[key]
    let bucket = map.get(bucketKey)
    if (!bucket) {
      bucket = { ourPoints: k.points, pyValues: new Map(), sampleEvidence: k.evidence }
      map.set(bucketKey, bucket)
    }
    bucket.pyValues.set(py, (bucket.pyValues.get(py) ?? 0) + 1)
  }
}

console.log('═══ STEP 2: per-koota overall agreement (calibrated direction) ═══')
for (const key of KOOTA_KEYS) {
  const t = koootaMismatchTotals[key]
  const total = t.match + t.mismatch
  console.log(`  ${key.padEnd(12)} ${t.match}/${total} = ${((t.match / total) * 100).toFixed(2)}% match`)
}

console.log('\n═══ STEP 3: per-bucket breakdown for directional/matrix kootas ═══')
for (const key of ['gana', 'varna', 'vashya', 'yoni', 'grahaMaitri', 'nadi'] as KootaKey[]) {
  console.log(`\n--- ${key} ---`)
  const map = buckets[key]
  const sortedKeys = [...map.keys()].sort()
  for (const bk of sortedKeys) {
    const b = map.get(bk)!
    const pyStr = [...b.pyValues.entries()].map(([v, c]) => `${v}(x${c})`).join(', ')
    const agree = b.pyValues.size === 1 && b.pyValues.has(b.ourPoints)
    const flag = agree ? 'OK' : 'DIVERGE'
    console.log(`  [${flag}] ${bk}: ours=${b.ourPoints}  pyjhora={${pyStr}}`)
  }
}

console.log('\n═══ STEP 4: Tara remainder-pair breakdown (bride→groom remainder, groom→bride remainder) ═══')
const taraBuckets = new Map<string, { ourPoints: number; pyValues: Map<number, number> }>()
for (const entry of raw.results) {
  if (entry.error) continue
  const boyNak = entry.boy_nakshatra
  const girlNak = entry.girl_nakshatra
  const brideNak = boyIsGroom ? girlNak : boyNak
  const groomNak = boyIsGroom ? boyNak : girlNak
  const b2g = taraRemainder(brideNak, groomNak)
  const g2b = taraRemainder(groomNak, brideNak)
  const perDirection = 1.5
  const ourPoints = (isTaraInauspicious(b2g) ? 0 : perDirection) + (isTaraInauspicious(g2b) ? 0 : perDirection)
  const py = pyPoints(entry, 'tara')
  if (py === null) continue
  const key = `b2g=${b2g},g2b=${g2b}`
  let bucket = taraBuckets.get(key)
  if (!bucket) {
    bucket = { ourPoints, pyValues: new Map() }
    taraBuckets.set(key, bucket)
  }
  bucket.pyValues.set(py, (bucket.pyValues.get(py) ?? 0) + 1)
}
for (const key of [...taraBuckets.keys()].sort()) {
  const b = taraBuckets.get(key)!
  const pyStr = [...b.pyValues.entries()].map(([v, c]) => `${v}(x${c})`).join(', ')
  const agree = b.pyValues.size === 1 && b.pyValues.has(b.ourPoints)
  console.log(`  [${agree ? 'OK' : 'DIVERGE'}] ${key}: ours=${b.ourPoints}  pyjhora={${pyStr}}`)
}

console.log('\nDone.')
